# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = Category.create!([{ title: 'Естественные науки' },
                               { title: 'Гуманитарные науки' },
                               { title: 'Информационные технологии' }])

users = User.create!([{ name: 'Admin', email: "reboot@tut.by", password: "Reboot" },
                      { name: 'User', email: "user@example.com", password: "User1" }])

tests = Test.create!([{ title: 'Биология', level: 1, category_id: categories[0].id, author_id: users[0].id },
                      { title: 'Химия', level: 2, category_id: categories[0].id, author_id: users[0].id },
                      { title: 'История', level: 0, category_id: categories[1].id, author_id: users[0].id },
                      { title: 'TCP/IP', level: 3, category_id: categories[2].id, author_id: users[0].id }])

questions = Question.create!([{ body: 'Химическое вещество, которое разрушает веретено деления, что приводит к полиплоидии, называется:', test_id: tests[0].id },
                              { body: 'Вид состоит из нескольких …', test_id: tests[0].id },
                              { body: 'Исландцы относятся к расе:', test_id: tests[0].id },
                              { body: 'Наиболее древняя эра в геохронологической таблице Земли — это:', test_id: tests[0].id },
                              { body: 'Развитие животного (или человека) от зиготы до рождения, называется:', test_id: tests[0].id },
                              { body: 'При восстановлении альдегидов в присутствии катализатора можно получить:', test_id: tests[1].id },
                              { body: 'Для алкенов наиболее характерны реакции', test_id: tests[1].id },
                              { body: 'Растворимость твердых веществ с повышением температуры', test_id: tests[1].id },
                              { body: 'Заместители в бензольном кольце, относящиеся к ориентантам второго рода, ориентируют вновь вступающий заместитель в:', test_id: tests[1].id },
                              { body: 'Вещества, образующие при диссоциации в растворе ион водорода, относят к:', test_id: tests[1].id },
                              { body: 'Чтобы добиться лояльности польского и белорусского населения, Наполеон обещал:', test_id: tests[2].id },
                              { body: 'Основными причинами, побудившими к объединению балто-славянских земель, были:', test_id: tests[2].id },
                              { body: 'Первый раздел Речи Посполитой произошел в:', test_id: tests[2].id },
                              { body: 'Скорина (ок. 1490 — ок. 1551) был:', test_id: tests[2].id },
                              { body: 'Полонецкий универсал (1794) — это:', test_id: tests[2].id },
                              { body: 'Зачем нужна проверка, выполняемая протоколом ICMP?', test_id: tests[3].id },
                              { body: 'Какова роль скользящего окна в протоколе TCP?', test_id: tests[3].id },
                              { body: 'Если предположить, что МАС-адреса нет в ARP-таблице, то как отправитель находит МАС-адрес пункта назначения?', test_id: tests[3].id },
                              { body: 'Зачем в протоколе TCP используются открытые соединения с трехсторонним квитированием?', test_id: tests[3].id },
                              { body: 'Какое из приведенных ниже определений лучше всего описывает цель этажерочных структур протоколов группы TCP/IP?', test_id: tests[3].id }])

Answer.create!([{ body: 'аспирином', question_id: questions[0].id, correct: false },
                { body: 'колхицином', question_id: questions[0].id, correct: true },
                { body: 'лигазой', question_id: questions[0].id, correct: false },
                { body: 'инсектицидом', question_id: questions[0].id, correct: false },
                { body: 'популяций', question_id: questions[1].id, correct: true },
                { body: 'семей', question_id: questions[1].id, correct: false },
                { body: 'классов', question_id: questions[1].id, correct: false },
                { body: 'родов', question_id: questions[1].id, correct: false },
                { body: 'американской', question_id: questions[2].id, correct: false },
                { body: 'евразийской', question_id: questions[2].id, correct: true },
                { body: 'экваториальной', question_id: questions[2].id, correct: false },
                { body: 'негроидной', question_id: questions[2].id, correct: false },
                { body: 'протерозойская', question_id: questions[3].id, correct: false },
                { body: 'мезозойская', question_id: questions[3].id, correct: false },
                { body: 'архейская', question_id: questions[3].id, correct: true },
                { body: 'палеозойская', question_id: questions[3].id, correct: false },
                { body: 'филогенезом', question_id: questions[4].id, correct: false },
                { body: 'онтогенезом', question_id: questions[4].id, correct: false },
                { body: 'эмбриональным ', question_id: questions[4].id, correct: true },
                { body: 'постэмбриональным', question_id: questions[4].id, correct: false },
                { body: 'алкины', question_id: questions[5].id, correct: false },
                { body: 'алкены', question_id: questions[5].id, correct: false },
                { body: 'первичные спирты', question_id: questions[5].id, correct: true },
                { body: 'вторичные спирты', question_id: questions[5].id, correct: false },
                { body: 'электрофильного присоединения', question_id: questions[6].id, correct: true },
                { body: 'радикального замещения', question_id: questions[6].id, correct: false },
                { body: 'электрофильного замещения', question_id: questions[6].id, correct: false },
                { body: 'нуклеофильного замещения', question_id: questions[6].id, correct: false },
                { body: 'понижается', question_id: questions[7].id, correct: false },
                { body: 'остается без изменения', question_id: questions[7].id, correct: false },
                { body: 'повышается', question_id: questions[7].id, correct: true },
                { body: 'резко возрастает', question_id: questions[7].id, correct: false },
                { body: 'орто-положение', question_id: questions[8].id, correct: false },
                { body: 'пара-положение', question_id: questions[8].id, correct: false },
                { body: 'мета-положение', question_id: questions[8].id, correct: true },
                { body: 'в орто- и пара-положения', question_id: questions[8].id, correct: false },
                { body: 'солям', question_id: questions[9].id, correct: false },
                { body: 'кислотам', question_id: questions[9].id, correct: true },
                { body: 'щелочам', question_id: questions[9].id, correct: false },
                { body: 'основаниям', question_id: questions[9].id, correct: false },
                { body: 'богатое вознаграждение польской знати', question_id: questions[10].id, correct: false },
                { body: 'вернуть секвестрированные земли и имущество шляхты', question_id: questions[10].id, correct: false },
                { body: 'отменить крепостничество', question_id: questions[10].id, correct: false },
                { body: 'возродить Речь Посполитую', question_id: questions[10].id, correct: true },
                { body: 'брачные союзы', question_id: questions[11].id, correct: false },
                { body: 'религиозные', question_id: questions[11].id, correct: false },
                { body: 'этнические', question_id: questions[11].id, correct: false },
                { body: 'внешняя угроза и внутренняя раздробленность', question_id: questions[11].id, correct: true },
                { body: '1772 г', question_id: questions[12].id, correct: true },
                { body: '1731 г', question_id: questions[12].id, correct: false },
                { body: '1764 г', question_id: questions[12].id, correct: false },
                { body: '1775 г', question_id: questions[12].id, correct: false },
                { body: 'государственным деятелем', question_id: questions[13].id, correct: false },
                { body: 'первопечатником, ученым, просветителем', question_id: questions[13].id, correct: true },
                { body: 'ректором Виленского университета', question_id: questions[13].id, correct: false },
                { body: 'богословом', question_id: questions[13].id, correct: false },
                { body: 'государственное учреждение в Речи Посполитой', question_id: questions[14].id, correct: false },
                { body: 'закон, принятый Сеймом', question_id: questions[14].id, correct: false },
                { body: 'организация в Великом княжестве Литовском', question_id: questions[14].id, correct: false },
                { body: 'обращение Т. Костюшко к населению Речи Посполитой', question_id: questions[14].id, correct: true },
                { body: 'для проверки полноты мониторинга всех действий в сети', question_id: questions[15].id, correct: false },
                { body: 'чтобы определить, находится сеть в режиме управления или в пользовательском режиме', question_id: questions[15].id, correct: false },
                { body: 'чтобы выяснить, достигают ли сообщения пункта назначения, и если нет — для определения возможных причин этого', question_id: questions[15].id, correct: true },
                { body: 'для определения соответствия настройки сети модели', question_id: questions[15].id, correct: false },
                { body: 'оно делает окно большим, поэтому за один раз может проходить больший объем данных, что приводит к более эффективному использованию полосы пропускания', question_id: questions[16].id, correct: false },
                { body: 'при приеме данных размер окна регулируется для каждого раздела дейтаграммы, что приводит к более эффективному использованию полосы пропускания', question_id: questions[16].id, correct: false },
                { body: 'оно позволяет во время TCP-сеанса динамически согласовывать размер окна, что приводит к более эффективному использованию полосы пропускания', question_id: questions[16].id, correct: true },
                { body: 'оно ограничивает объем поступающих данных, так что каждый сегмент должен посылаться по одному, что приводит к неэффективному использованию полосы пропускания', question_id: questions[16].id, correct: false },
                { body: 'посылает широковещательное сообщение по всей сети', question_id: questions[17].id, correct: false },
                { body: 'посылает широковещательное сообщение по всей локальной сети', question_id: questions[17].id, correct: true },
                { body: 'в поисках адреса посылает сообщение по всем адресам', question_id: questions[17].id, correct: false },
                { body: 'сверяется с таблицей маршрутизации', question_id: questions[17].id, correct: false },
                { body: 'для определения объема информации, который принимающая станция может принять за один раз', question_id: questions[18].id, correct: false },
                { body: 'для восстановления данных, если потом возникнут проблемы', question_id: questions[18].id, correct: true },
                { body: 'для эффективного использования пользователями полосы пропускания', question_id: questions[18].id, correct: false },
                { body: 'для преобразования двоичных ответов на команду ping в информацию для более высоких уровней модели OSI', question_id: questions[18].id, correct: false },
                { body: 'точно соответствуют верхним уровням модели OSI', question_id: questions[19].id, correct: false },
                { body: 'передают информацию в виде последовательности дейтаграмм', question_id: questions[19].id, correct: false },
                { body: 'в месте приема выполняют сборку дейтаграмм в полные сообщения', question_id: questions[19].id, correct: false },
                { body: 'поддерживают все стандартные протоколы физического и канального уровне', question_id: questions[19].id, correct: true }])
